name: Update RSS Feed HTML with Translation

on:
  schedule:
    - cron: '0 9 * * 1,3,5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production  # 必要に応じて設定
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade feedparser anthropic python-dotenv

      - name: Run Python script
        run: python generate_html.py
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.html
          git commit -m "Update RSS feed HTML with Claude translations" || echo "No changes to commit"
          git push